import type { ComponentType } from 'react'
import {
  Activity,
  AlertOctagon,
  BarChart4,
  BadgeCheck,
  Boxes,
  Building2,
  CalendarDays,
  CheckCircle,
  ClipboardList,
  Contact,
  Database,
  Factory,
  FileCheck,
  FilePlus,
  FileSignature,
  FileText,
  Hammer,
  Handshake,
  History,
  LayoutGrid,
  LayoutDashboard,
  LayoutList,
  LifeBuoy,
  LineChart,
  Monitor,
  PackageSearch,
  Presentation,
  Receipt,
  Search,
  Shield,
  ShoppingCart,
  Target,
  UserCog,
  Users,
  Wrench,
} from 'lucide-react'

export type IconComponent = ComponentType<{ className?: string }>

export const DefaultMenuIcon: IconComponent = FileText

export const IconMap: Record<string, IconComponent> = {
  Activity,
  AlertOctagon,
  BarChart4,
  BadgeCheck,
  Boxes,
  Building2,
  CalendarDays,
  CheckCircle,
  ClipboardList,
  Contact,
  Database,
  Factory,
  FileCheck,
  FilePlus,
  FileSignature,
  FileText,
  Hammer,
  Handshake,
  History,
  LayoutGrid,
  LayoutDashboard,
  LayoutList,
  LifeBuoy,
  LineChart,
  Monitor,
  PackageSearch,
  Presentation,
  Receipt,
  Search,
  Shield,
  ShoppingCart,
  Target,
  UserCog,
  Users,
  Wrench,
}

export function getIconByName(iconName: string | null | undefined): IconComponent {
  if (!iconName) return DefaultMenuIcon
  return IconMap[iconName] ?? DefaultMenuIcon
}
