server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /cockpit/;
  }

  location /cockpit/ {
    try_files $uri $uri/ /cockpit/index.html;
  }
}

