name: aygjm-sso-dev

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: ["start-dev", "--http-port=8080", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: "${KC_DB_HOST:-host.docker.internal}"
      KC_DB_URL_PORT: "${KC_DB_PORT:-33705}"
      KC_DB_URL_DATABASE: ${KC_DB_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: "xforwarded"
    ports:
      - "${KC_HTTP_PORT}:8080"
    volumes:
      - kc_data:/opt/keycloak/data
      - ./realm:/opt/keycloak/data/import:ro

volumes:
  kc_data:
